<a href="https://colab.research.google.com/github/rijul69/DATASCIENCE-ASSIGNMENTS/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Q1 — Array Creation

In [2]:
import numpy as np

arr = np.arange(1, 21)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q2 — Zeros and Ones Array

In [3]:
zeros = np.zeros((4,5))
ones = np.ones((4,5))

result = zeros + ones

print(result)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Q3 — linspace()

In [4]:
arr = np.linspace(0, 1, 8)

print(arr)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


Q4 — Reshaping

In [5]:
arr = np.arange(1,25).reshape(4,6)

print(arr)

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
Dimensions: 2
Data Type: int64


Q5 — 1D Slicing

In [6]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

# a
print("First 5:", arr[:5])

# b
print("Last 3:", arr[-3:])

# c
print("Alternate:", arr[::2])

First 5: [10 20 30 40 50]
Last 3: [ 80  90 100]
Alternate: [10 30 50 70 90]


Q6 — 2D Slicing

In [11]:
arr = np.arange(25).reshape(5,5)

print(arr)


print("Row 2:", arr[1])


print("Column 3:", arr[:,2])


print("Top Right Block:")
(arr[:3,2:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 2: [5 6 7 8 9]
Column 3: [ 2  7 12 17 22]
Top Right Block:


array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

Q7 — Broadcasting

In [17]:
a = np.array([1,2,3,4,5])

print("Add 100:", a + 100)

print("Multiply by 3:", a * 3)

Add 100: [101 102 103 104 105]
Multiply by 3: [ 3  6  9 12 15]


Q8 — Element-wise Operations

In [13]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


Q9 — Statistical Operations

In [14]:
scores = np.array([72,85,91,68,74,88,62,95,77,80])

print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Standard Deviation:", np.std(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Range:", np.max(scores) - np.min(scores))

Mean: 79.2
Median: 78.5
Standard Deviation: 10.02796090937734
Minimum: 62
Maximum: 95
Range: 33



Q10 — Random Integer Array

In [15]:
arr = np.random.randint(1,100,size=(3,4))

print(arr)

print("Total Sum:", np.sum(arr))

print("Row-wise Sum:", np.sum(arr, axis=1))

print("Column-wise Mean:", np.mean(arr, axis=0))

[[75  7 41 96]
 [67 49 86 28]
 [46  7 58 16]]
Total Sum: 576
Row-wise Sum: [219 230 127]
Column-wise Mean: [62.66666667 21.         61.66666667 46.66666667]


BONUS  QUESTION

In [18]:
arr = np.random.normal(loc=50, scale=10, size=1000)

print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Mean: 50.035629022539425
Standard Deviation: 9.652346054857478


**Yes, the values are close to 50 and 10 because the numbers are generated using a normal distribution with mean = 50 and std = 10.**